/////////////////////////////////////////////////////////////////////
// Prescription Claims Analysis Project
// Isabel Bennett
// Spring 2026, SEIS 732
//
// Purpose: Transform raw prescription claims data into a
// structured, analysis friendly format.
/////////////////////////////////////////////////////////////////////

// Initial Setup 
USE ROLE TRAINING_ROLE;

CREATE WAREHOUSE IF NOT EXISTS CHIPMUNK_WH;
USE WAREHOUSE CHIPMUNK_WH;
CREATE DATABASE IF NOT EXISTS CHIPMUNK_DB;
USE DATABASE CHIPMUNK_DB;

// Create schehma for aggregation layer to optimize data for analysis
CREATE OR REPLACE SCHEMA CHIPMUNK_AGGREGATION;

// Set schema to aggregation layer
USE SCHEMA CHIPMUNK_AGGREGATION;

// Aggregation layer overview:
// These views provide summarized perspectives about affordability, 
// claim timing, geography, demographics, refill behavior, and 
// prescription supply patterns

// Set schema to aggregation layer
USE SCHEMA CHIPMUNK_AGGREGATION;


// Step 1: Create Cost Burden Distribution
// Supports affordability analysis
CREATE OR REPLACE VIEW AGG_COST_BURDEN_DISTRIBUTION AS
SELECT
    COST_BURDEN_CATEGORY,
    COUNT(*) AS TOTAL_CLAIMS,
    AVG(TOTAL_MEMBER_PAID) AS AVG_MEMBER_PAID,
    AVG(MEMBER_SAVINGS) AS AVG_MEMBER_SAVINGS,
    AVG(MEMBER_COST_BURDEN_RATIO) AS AVG_COST_BURDEN_RATIO,
    MIN (CASE
        WHEN IS_REVERSED_CLAIM = FALSE AND TOTAL_MEMBER_PAID >= 0
        THEN TOTAL_MEMBER_PAID
    END) AS MIN_MEMBER_PAID,
    MAX (CASE 
        WHEN IS_REVERSED_CLAIM = FALSE AND TOTAL_MEMBER_PAID >= 0
        THEN TOTAL_MEMBER_PAID
    END) AS MAX_MEMBER_PAID
FROM CHIPMUNK_CURATION.CUR_RX_WEEKLY
GROUP BY COST_BURDEN_CATEGORY;

// Validate aggregation
SELECT *
FROM AGG_COST_BURDEN_DISTRIBUTION
ORDER BY TOTAL_CLAIMS DESC;
    
// Step 2: Create Fill-to-Submit Experience
// Supports analysis of timing related to member payment and savings
CREATE OR REPLACE VIEW AGG_FILL_SUBMIT_EXPERIENCE AS
SELECT 
    FILL_AND_SUBMIT_SPEED_CATEGORY,
    COUNT(*) AS TOTAL_CLAIMS,
    AVG(DAYS_BETWEEN_FILL_AND_SUBMIT) AS AVG_DAYS_BETWEEN_FILL_AND_SUBMIT,
    AVG(TOTAL_MEMBER_PAID) AS AVG_MEMBER_PAID,
    AVG(MEMBER_SAVINGS_PERCENT) AS AVG_MEMBER_SAVINGS_PERCENT,
    SUM(TOTAL_MEMBER_PAID) AS TOTAL_MEMBER_PAID_SUM
FROM CHIPMUNK_CURATION.CUR_RX_WEEKLY
WHERE IS_REVERSED_CLAIM = FALSE AND TOTAL_MEMBER_PAID >= 0
GROUP BY FILL_AND_SUBMIT_SPEED_CATEGORY;

// Validate aggregation
SELECT *
FROM AGG_FILL_SUBMIT_EXPERIENCE
ORDER BY TOTAL_CLAIMS DESC;

// Step 3: State Level Patient Experience
// Supports geographic analysis
CREATE OR REPLACE VIEW AGG_STATE_PATIENT_EXPERIENCE AS
SELECT
    MEMBER_STATE,
    COUNT(*) AS TOTAL_CLAIMS,
    COUNT(DISTINCT PHARMACY_NAME) AS DISTINCT_PHARMACIES,
    AVG(MEMBER_COST_BURDEN_RATIO) AS AVG_COST_BURDEN_RATIO,
    AVG(DAYS_BETWEEN_FILL_AND_SUBMIT) AS AVG_DAYS_BETWEEN_FILL_AND_SUBMIT,
    AVG(MEMBER_SAVINGS_PERCENT) AS AVG_MEMBER_SAVINGS_PERCENT,
    AVG(TOTAL_MEMBER_PAID) AS AVG_MEMBER_PAID
FROM CHIPMUNK_CURATION.CUR_RX_WEEKLY
WHERE MEMBER_STATE IS NOT NULL 
GROUP BY MEMBER_STATE;
 
// Validate aggregation
SELECT *
FROM AGG_STATE_PATIENT_EXPERIENCE
ORDER BY TOTAL_CLAIMS DESC;

// Step 4: Age Group Experience
// Supports democraphic analysis
CREATE OR REPLACE VIEW AGG_AGE_GROUP_EXPERIENCE AS 
SELECT
    MEMBER_AGE_SEGMENT,
    COUNT(*) AS TOTAL_CLAIMS,
    AVG(TOTAL_MEMBER_PAID) AS AVG_MEMBER_PAID,
    AVG(TOTAL_DRUG_COST) AS AVG_TOTAL_DRUG_COST,
    AVG(MEMBER_SAVINGS) AS AVG_MEMBER_SAVINGS,
    AVG(MEMBER_SAVINGS_PERCENT) AS AVG_MEMBER_SAVINGS_PERCENT,
    AVG(MEMBER_COST_BURDEN_RATIO) AS AVG_COST_BURDEN_RATIO
FROM CHIPMUNK_CURATION.CUR_RX_WEEKLY
GROUP BY MEMBER_AGE_SEGMENT;

// Validate aggregation
SELECT *
FROM AGG_AGE_GROUP_EXPERIENCE
ORDER BY TOTAL_CLAIMS DESC;

// Step 5: Refill Stage Analysis
// Support analysis of how refill stages relate to supply,
// payment, and cost burden
CREATE OR REPLACE VIEW AGG_REFILL_STAGE_ANALYSIS AS
SELECT
    REFILL_STAGE_CATEGORY,
    COUNT(*) AS TOTAL_CLAIMS,
    AVG(REFILL_NUMBER) AS AVG_REFILL_NUMBER,
    AVG(TOTAL_DAYS_SUPPLY) AS AVG_TOTAL_DAYS_SUPPLY,
    AVG(TOTAL_MEMBER_PAID) AS AVG_MEMBER_PAID,
    AVG(MEMBER_COST_BURDEN_RATIO) AS AVG_COST_BURDEN_RATIO
FROM CHIPMUNK_CURATION.CUR_RX_WEEKLY
GROUP BY REFILL_STAGE_CATEGORY;

// Validate aggregation
SELECT *
FROM AGG_REFILL_STAGE_ANALYSIS
ORDER BY TOTAL_CLAIMS DESC;

// Step 6: Supply Type Analysis
// Supports analysis of how supply lengths change cost
// and savings
CREATE OR REPLACE VIEW AGG_SUPPLY_TYPE_ANALYSIS AS
SELECT
    SUPPLY_TYPE,
    COUNT(*) AS TOTAL_CLAIMS,
    AVG(TOTAL_DAYS_SUPPLY) AS AVG_TOTAL_DAYS_SUPPLY,
    AVG(TOTAL_MEMBER_PAID) AS AVG_MEMBER_PAID,
    AVG(MEMBER_SAVINGS) AS AVG_MEMBER_SAVINGS,
    AVG(MEMBER_COST_BURDEN_RATIO) AS AVG_COST_BURDEN_RATIO,
    MAX(TOTAL_DRUG_COST) AS MAX_TOTAL_DRUG_COST
FROM CHIPMUNK_CURATION.CUR_RX_WEEKLY
GROUP BY SUPPLY_TYPE;

// Validate aggregation
SELECT *
FROM AGG_SUPPLY_TYPE_ANALYSIS
ORDER BY SUPPLY_TYPE;

// Step 7: Create a Materialized View for frequently used state cost burden metrics
CREATE OR REPLACE MATERIALIZED VIEW MV_STATE_COST_BURDEN AS
SELECT  
    MEMBER_STATE,
    COUNT(*) AS TOTAL_CLAIMS,
    AVG(MEMBER_COST_BURDEN_RATIO) AS AVG_COST_BURDEN_RATIO,
    AVG(TOTAL_MEMBER_PAID) AS AVG_MEMBER_PAID,
    AVG(MEMBER_SAVINGS_PERCENT) AS AVG_MEMBER_SAVINGS_PERCENT
FROM CHIPMUNK_CURATION.CUR_RX_WEEKLY
WHERE MEMBER_STATE IS NOT NULL
GROUP BY MEMBER_STATE;

// Validate materialized view 
SELECT *
FROM MV_STATE_COST_BURDEN
ORDER BY TOTAL_CLAIMS DESC;
